[workspace.package]
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
edition = "2021"
rust-version = "1.80"

[package]
name = "block_compression"
description = "Texture block compression using WGPU compute shader"
version = "0.1.0"
license = "MIT"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords = ["texture", "image", "compress", "wgpu"]
categories = ["rendering", "rendering::engine", ]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true }

[dev-dependencies]
intel_tex_2 = "0.4"
image = { workspace = true, features = ["png"] }
pollster = { workspace = true }

[workspace.dependencies]
bytemuck = "1.21"
ddsfile = "0.5"
image = { version = "0.25", default-features = false }
pollster = "0.4"
wgpu = "23"

[workspace]
members = [
    "compressor",
]
